// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package ioutils

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson77835261DecodeGithubComVoyakinHLokleBackendInternalPkgIoutils(in *jlexer.Lexer, out *ModelError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "message":
			out.Message = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson77835261EncodeGithubComVoyakinHLokleBackendInternalPkgIoutils(out *jwriter.Writer, in ModelError) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Message != "" {
		const prefix string = ",\"message\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ModelError) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson77835261EncodeGithubComVoyakinHLokleBackendInternalPkgIoutils(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ModelError) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson77835261EncodeGithubComVoyakinHLokleBackendInternalPkgIoutils(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ModelError) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson77835261DecodeGithubComVoyakinHLokleBackendInternalPkgIoutils(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ModelError) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson77835261DecodeGithubComVoyakinHLokleBackendInternalPkgIoutils(l, v)
}
func easyjson77835261DecodeGithubComVoyakinHLokleBackendInternalPkgIoutils1(in *jlexer.Lexer, out *JSON) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = int(in.Int())
		case "body":
			if m, ok := out.Body.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Body.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Body = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson77835261EncodeGithubComVoyakinHLokleBackendInternalPkgIoutils1(out *jwriter.Writer, in JSON) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Status))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		if m, ok := in.Body.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Body.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Body))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v JSON) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson77835261EncodeGithubComVoyakinHLokleBackendInternalPkgIoutils1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v JSON) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson77835261EncodeGithubComVoyakinHLokleBackendInternalPkgIoutils1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *JSON) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson77835261DecodeGithubComVoyakinHLokleBackendInternalPkgIoutils1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *JSON) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson77835261DecodeGithubComVoyakinHLokleBackendInternalPkgIoutils1(l, v)
}
